### ISSUE TITLE
add link to the Github Pages URL in the description?

### ISSUE THREAD

**Issue by diraneyya** [Tetre101/Guess-A-number-Js-Game#4]
For people to play your game without having to download it or run it locally it would make sense for you to deploy it on GitHub pages and put a link in the description.

**Comment by Tetre101** [comment]
sorted

**Comment by diraneyya** [comment]
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/107997002/220942603-5b6eb092-8147-4b25-a9e3-96acd614d20c.png">

Does not look like it was sorted to me 😛
